### ISSUE TITLE
React Datepicker

### ISSUE THREAD

**Issue by benct** [fabric-ds/issues#17]
As requested, I'm creating an issue for outlining our team (Travel) needs for a React datepicker component in Fabric.

Travel uses datepickers on almost all sub-verticals and as we are in the process of upgrading some of them to Fabric, we need a datepicker component that supports the new design. We are mostly using Troika's React datepicker, as can be seen under the different vertical tabs [here](https://www.finn.no/reise/). This component does not work with Fabric, as its CSS crashes with fabric CSS (there are probably workarounds for that, but it would still be better with a component designed to work with Fabric). Additionally, we need some new features that are not supported by Troikas datepicker.

### Basic functionality:

- Most (if not all) current functionality of Troikas React date(range)picker.

I'm guessing that porting the current datepicker component from troika would be the easiest solution to support all basic functionality and it would make it easier for us to swap out/upgrade the component usage too.

### Additional functionality:

For Feriehus (FHH), we need some added functionality for providing more detailed booking and pricing info for our users. We are currently using an old standalone JS library (Kalendae) for some parts of this, so we desperately need something better to replace it with, that also supports our new (and old) use cases.

#### Booked dates:
- Support for specifying ranges of booked dates.
- Rendering start/end days as "half days" (see illustration).
- Interaction for these dates can be disabled or customised (eg. clicking a range triggers a popup with booking info).
- *Not a priority, but nice to have:* Display custom text across booked date range (see illustration).

This could be somewhat similar to the existing `isDayDisabled`, however the start/end dates need to be rendered differently.

#### Custom day/cell/range rendering:

On admin pages for an FHH ad, we want to display a bigger calendar (non-popover) with more detailed info per day, for example with a price or booking (see illustration). Adding support for custom rendering of a cell or range in the calendar view should cover most use cases. This could also be used for rendering "half days", if not handled separately as described above.

![image](https://user-images.githubusercontent.com/14112103/142447240-3ec35192-37a4-4641-8f6a-1948833a8676.png)

![image](https://user-images.githubusercontent.com/14112103/142449434-773f5408-e840-450e-94fa-21e3d6d418cf.png)

(examples only, does not need to look exactly like this)

**Comment by benja** [comment]
After discussion back and forth through Slack, we have delivered a date picker with fabric styles and support for booked date ranges. See source code [here](https://github.schibsted.io/finn/legacy-fabric-datepicker).
