### ISSUE TITLE
React breadcrumbs support for nested children

### ISSUE THREAD

**Issue by vsandvold** [fabric-ds/issues#20]
The Fabric React `Breadcrumbs` component does not support nested children, and breaks in a few (edge) cases when child components are not a plain flat list of anchor elements.

Example of breadcrumbs with a single child:
```jsx
<Breadcrumbs>
  <a href="#/url/1" aria-current="page">
    Torget
  </a>
</Breadcrumbs>
``` 

Example of breadcrumbs with nested children:
```jsx
<Breadcrumbs>
  <a href="#/url/1">Eiendom</a>
  <>
    <a href="#/url/2">Bolig til salgs</a>
    <>
      <a href="#/url/3" aria-current="page">
        Oslo
      </a>
    </>
  </>
</Breadcrumbs>
```

These examples either render incorrectly (or throw an error) when rendering the `Breadcrumbs` component. A live example can be found here https://codesandbox.io/s/lucid-jasper-nxco0?file=/src/App.js

Screenshot of breadcrumbs with nested children that render without `/` in between:
![Skjermbilde 2021-12-07 kl  15 38 44](https://user-images.githubusercontent.com/6734787/145049561-bc3963f5-55d8-438a-9806-0f02e7d1572f.png)

One possible solution could be to wrap the `children` prop in `React.Children.toArray(children)` to flatten the array before before mapping https://github.com/fabric-ds/react/blob/main/packages/breadcrumbs/src/component.tsx#L16

**Comment by benja** [comment]
The issue here seems to be that the collection is returned as an object that doesn't easily map into the correct structure:

```js
const collection = {
  name: "Gucci",
  url: "#/url/3",
  parent: {
    name: "Luksusvesker",
    url: "#/url/2",
    parent: {
      name: "Sex and the City",
      url: "#/url/1"
    }
  }
};
```

What we can do is recursively loop through the object and build an array of objects that we can map through and render the anchor elements with.

Here's a code example on how to achieve this: https://codesandbox.io/s/gifted-butterfly-8ionp?file=/src/App.js:0-805.

**Comment by vsandvold** [comment]
Thank you, we also fixed this issue outside of the component by flattening the nested data structure into a list before mapping to link elements. However, I think it would be better if the component handled the flattening itself. The component should also handle a single child element, which it currently does not (it throws an error).

The problem, as I see it, is that the component assumes the `children` prop to be a flat list that it can call `.map()` on. This may result in unexpected behavior and errors, since `children` can be both a list, a single element, and a nested structure. The docs tells us that the Breadcrumbs component children should be links, but this requirement is not enforced. And the way ´React.Fragment` works in this specific context can be a bit misleading, since the nested structure of fragments is not visible when rendered to markup. 

I can imagine a few different solutions, depending on how you want the component to behave.

**1. React.Children.toArray**

One solution is to wrap the `children` prop in `React.Children.toArray` before calling map, like this: 
```
React.Children.toArray(children).map(() => <render crumbs>)
```
This will work for both a single child element, a flat list and a nested structure.

**2. Throw an error**

Another solution is to add some checks for `children`, if it's an array or just a single element, and then render accordingly. However, this leaves the behavior for nested structures still undefined. It's also possible to throw an error if the component children is not a flat list of links, helping devs understand that they are using the component incorrectly.

I personally think 1) is a good solution here. WDYT?

**Comment by vsandvold** [comment]
It turns out I was wrong about `React.Children.toArray`, which does not flatten nested elements (but rather just lists of elements) https://github.com/facebook/react/issues/6889#issuecomment-221858162

I would be very happy if you could find a different way to support nested structures with fragments.

**Comment by benja** [comment]
I've updated the component to now flatten the children passed through. The `React.Children.toArray` did not seem to work, so I ended up having to go for the same recursive solution as the CSB example above. https://github.com/fabric-ds/react/pull/66

**Comment by benja** [comment]
https://github.com/fabric-ds/react/pull/66#issuecomment-1001956905
