### ISSUE TITLE
React components don't work in Safari 12

### ISSUE THREAD

**Issue by vsandvold** [fabric-ds/issues#27]
We ran into an issue with older Safari browsers when using the Fabric React components. Rendering any of the components result in an error similar to the one you see in this screenshot[^screenshot].

It looks like the `element-collapse` lib is [using the `Window.matchMedia()` API in a way that is correct](https://github.com/fabric-ds/element-collapse/blob/master/index.js#L6-L8), but not supported in Safari 12. Specifically, Safari prior to v14 implements `MediaQueryList.addListener()` instead of `EventTarget.addEventListener()`, as described here https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

If we aim to support Safari prior to v14, we will need a suitable workaround. If not, we just have to communicate that clearly to our users. It did create some noise when we tried, and we decided to roll back. I'm happy with either, just as long as we have control 🙂

[^screenshot]:
    ![IMG_D3AC78A63FCD-1](https://user-images.githubusercontent.com/6734787/147503020-869bd02c-18c6-4740-82fe-337f1caa6300.jpeg)

**Comment by benja** [comment]
Thank you for reporting this. We'll be publishing a new version of Fabric today with an updated version of `element-collapse` which should solve this issue.
