### ISSUE TITLE
React Modal has bad behavior on widths/resize

### ISSUE THREAD

**Issue by pearofducks** [fabric-ds/issues#66]
https://sch-chat.slack.com/archives/G018TRDBXPE/p1645520100029659

"Found the reason. In the react version the div with class f-modal, is wrapped in another div, with no classes. Guess it messes up margins from the “f-modal”.
Removing it solves the problem."

Check if the Troika version is also bugging out.

**Comment by benja** [comment]
I cannot reproduce. Seems to be working fine in the [docs](https://react.fabric-ds.io/modal) now?
