### ISSUE TITLE
Expose ToggleItem

### ISSUE THREAD

**Issue by digitalsadhu** [fabric-ds/issues#99]
We've had a request for a checkbox in React that goes outside the scope of the standard checkbox. The current suggestion is that we expose ToggleItem as a building block so that teams can build their own for custom needs.

See: https://sch-chat.slack.com/archives/C01GYKPJVFT/p1655788904549869

**Comment by BalbinaK** [comment]
PR: https://github.com/fabric-ds/react/pull/135
